services:
  # Apache webserver service
  webserver:
    container_name: sqli-PHP-webServer
    build:
    # Dockerfile path
      context: .
      dockerfile: Dockerfile  
    # Mount the local ./app directory to /var/www/html in the container
    volumes:
      - ./app:/var/www/html 
    # Map port 4000 on the host to port 80 on the container 
    ports:
      - 4000:80
    depends_on:
    - postgres

  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: .UYr930Qr
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      # Default email for pgAdmin 4
      PGADMIN_DEFAULT_EMAIL: adminServer@email.com
      # Password for accessing pgAdmin 4
      PGADMIN_DEFAULT_PASSWORD: 1D4sNQ75J@c
    ports:
      # Expose pgadmin on 5050 
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  pgadmin_data:
